In [1]:
import pandas as pd
import numpy as np

from matplotlib import pyplot as plt
from scipy.stats import linregress 

In [2]:

my_arr = np.arange(1_000_000)


In [3]:
my_list = list(range(1_000_000))


In [4]:
%timeit my_arr2 = my_arr * 2

699 µs ± 3.65 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
%timeit my_list2 = [x * 2 for x in my_list]

26.5 ms ± 297 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
rand_array = np.random.rand(2, 3)

In [8]:
rand_array

array([[0.19628299, 0.56972204, 0.32814351],
       [0.41689847, 0.9870636 , 0.74485751]])

In [10]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a = np.random.rand(2, 3, 4)
a

array([[[0.44731408, 0.09391701, 0.08124115, 0.13064186],
        [0.79888265, 0.54970731, 0.59351101, 0.88308235],
        [0.52663893, 0.07849054, 0.45931085, 0.72176698]],

       [[0.03609782, 0.41198826, 0.04482076, 0.47408953],
        [0.70886973, 0.31853931, 0.52029919, 0.80773506],
        [0.9416732 , 0.20049839, 0.16715513, 0.2784289 ]]])

In [21]:
a[1, 0: 2, 1:]

array([[0.41198826, 0.04482076, 0.47408953],
       [0.31853931, 0.52029919, 0.80773506]])

In [22]:
a.ndim

3

In [23]:
a.dtype

dtype('float64')

In [24]:
from timeit import Timer

In [25]:
my_list = list(range(10**6))
my_array = np.array(my_list)

In [26]:
def for_add():
    return [item + 1 for item in my_list]

def vec_add():
    return my_array + 1

In [27]:
print('For-loop addition:')
print(min(Timer(for_add).repeat(10, 10)))
print('Vectorized addition:')
print(min(Timer(vec_add).repeat(10, 10)))


For-loop addition:
0.24130170800162887
Vectorized addition:
0.004507166999246692


In [30]:
def for_mul():
    return [item * 2 for item in my_list]
def vec_mul():
    return my_array * 2
print('For-loop multiplication:')
print(min(Timer(for_mul).repeat(10, 10)))
print('Vectorized multiplication:')
print(min(Timer(vec_mul).repeat(10, 10)))

For-loop multiplication:
0.2535759999991569
Vectorized multiplication:
0.0038080000012996607


In [33]:
import math
def for_sqrt():
    return [math.sqrt(item) for item in my_list]
def vec_sqrt():
    return np.sqrt(my_array)
print('For-loop square root:')
print(min(Timer(for_sqrt).repeat(10, 10)))
print('Vectorized square root:')
print(min(Timer(vec_sqrt).repeat(10, 10)))

For-loop square root:
0.5964930829995865
Vectorized square root:
0.007913667001048452


In [34]:
sample = np.random.normal()

In [35]:
sample

-1.8529191602981443

In [38]:
sample = np.random.normal(loc=100, scale=10, size=(2, 3))
sample

array([[116.05088864, 107.12617494, 108.03223714],
       [106.09458801, 101.57443291, 104.07068436]])

In [41]:
samples = np.random.poisson(lam=100, size=(2, 3))
samples

array([[ 91, 103, 107],
       [ 98,  93,  92]])

In [49]:
my_dict = {'coll1': [2, 1, 4], 'col2': np.array([3, 4, 2]), 'col3': [4, 5,6], 'col4': np.array([7,3, 4]),}

df = pd.DataFrame(my_dict)
df

coll1  col2  col3  col4
0      2     3     4     7
1      1     4     5     3
2      4     2     6     4

In [50]:
df.loc[2]

coll1    4
col2     2
col3     6
col4     4
Name: 2, dtype: int64

In [52]:
df.loc[2, ['col2', 'col3']]

col2    2
col3    6
Name: 2, dtype: int64